name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using a custom LLM API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  CUSTOM_API_KEY:
    description: "API key for your custom LLM endpoint (e.g. RunPod)."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
